---
- name: Include prepare.yml
  ansible.builtin.import_tasks: prepare.yml

- name: Include firmware.yml
  ansible.builtin.import_tasks: firmware.yml

- name: Include vocalfusion.yml
  ansible.builtin.import_tasks: vocalfusion.yml

- name: Include touchscreen.yml
  ansible.builtin.import_tasks: touchscreen.yml

- name: Include wireplumber.yml
  ansible.builtin.import_tasks: wireplumber.yml
