---
- name: Reload Systemd User
  become: true
  become_user: "{{ ovos_installer_user }}"
  ansible.builtin.systemd_service:
    daemon_reload: true
    scope: user

- name: Load Module
  ansible.builtin.command:
    cmd: |
      depmod -a {{ ansible_kernel }}
      modprobe -v vocalfusion-soundcard
  changed_when: false
