---
- name: Reload Systemd User
  become: true
  become_user: "{{ ovos_installer_user }}"
  ansible.builtin.systemd_service:
    daemon_reload: true
    scope: user

- name: Run Depmod
  ansible.builtin.command:
    cmd: |
      depmod -a {{ _ovos_hardware_mark2_kernel_target }}
  changed_when: false
