---
- name: Reload Systemd User
  become: true
  become_user: "{{ ovos_installer_user }}"
  ansible.builtin.systemd_service:
    daemon_reload: true
    scope: user

- name: Run Depmod
  ansible.builtin.command:
    cmd: |
      depmod -a {{ ansible_kernel }}
  changed_when: false

- name: Set Reboot
  ansible.builtin.set_fact:
    ovos_installer_reboot: true
