---
- name: Handle virtualenv package requirements (ovos-core)
  ansible.builtin.apt:
    name:
      - swig
      - libfann-dev
      - libasound2-dev
      - libpulse-dev
      - flac
      - mpg123
      - music123
      - sox
      - libsox-fmt-all
      - vlc
    state: "{{ ovos_installer_uninstall }}"
  when: ansible_os_family == "Debian"
  tags:
    - always

- name: Handle virtualenv package requirements (ovos-core)
  ansible.builtin.dnf:
    name:
      - gcc-c++
      - swig
      - fann-devel
      - alsa-lib-devel
      - pulseaudio-libs-devel
      - flac123
      - mpg123
      - sox
      - vlc-core
    state: "{{ ovos_installer_uninstall }}"
  when: ansible_os_family == "RedHat"
  tags:
    - always
