---
- name: Add {{ ovos_installer_user }} to dialout group
  ansible.builtin.user:
    name: "{{ ovos_installer_user }}"
    groups: dialout
    append: true

- name: Create directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ ovos_installer_user }}"
    group: "{{ ovos_installer_group }}"
    mode: "0755"
  loop:
    - "{{ ovos_installer_user_home }}/.config/systemd/user"
    - "{{ _ovos_hardware_mark1_workind_directory }}"

- name: Configure initialize.sh to {{ _ovos_hardware_mark1_workind_directory }}
  ansible.builtin.copy:
    src: initialize.sh
    dest: "{{ _ovos_hardware_mark1_workind_directory }}/initialize.sh"
    owner: "{{ ovos_installer_user }}"
    group: "{{ ovos_installer_group }}"
    mode: "0755"
