---
- name: Install linux-cpupower
  ansible.builtin.apt:
    name: linux-cpupower
  when: ansible_os_family == "Debian"

- name: Install kernel-tools
  ansible.builtin.apt:
    name: kernel-tools
  when: ansible_os_family == "RedHat"

- name: Copy cpu-governor systemd unit file
  ansible.builtin.copy:
    src: tuning/cpu-governor.service
    dest: /etc/systemd/system/cpu-governor.service
    owner: root
    group: root
    mode: "0644"
  notify: Reload Systemd

- name: Flush handlers cpu-governor
  ansible.builtin.meta: flush_handlers

- name: Enable and start systemd cpu-governor unit
  ansible.builtin.systemd:
    name: cpu-governor.service
    enabled: true
    force: true
    state: started
