---
# Thanks to https://www.xephixus.com/2019/12/11/testing/
- name: Add noatime option
  ansible.builtin.replace:
    path: /etc/fstab
    regexp: '^(\S+)(\s+)(\S+)(\s+)(ext4|xfs|btrfs)(\s+)(((?!noatime)\S)*)(\s+)(\d)(\s+)(\d)$'
    replace: '\1\2\3\4\5\6\7,noatime\9\10\11\12'
    backup: true
  notify: Reload Systemd

- name: Add nodiratime option
  ansible.builtin.replace:
    path: /etc/fstab
    regexp: '^(\S+)(\s+)(\S+)(\s+)(ext4|xfs|btrfs)(\s+)(((?!nodiratime)\S)*)(\s+)(\d)(\s+)(\d)$'
    replace: '\1\2\3\4\5\6\7,nodiratime\9\10\11\12'
    backup: true
  notify: Reload Systemd

- name: Flush handlers fstab
  ansible.builtin.meta: flush_handlers
