---
- name: Load i2c-dev and spidev kernel modules
  community.general.modprobe:
    name: "{{ item }}"
    persistent: present
  loop:
    - i2c-dev
    - spidev

- name: Check for /boot/firmware directory
  ansible.builtin.stat:
    path: /boot/firmware
  register: _boot_config_status

- name: Manage I2C, SPI and I2S buses
  vars:
    _boot_directory: "{{ '/boot/firmware' if _boot_config_status.stat.exists | bool else '/boot' }}"
  ansible.builtin.lineinfile:
    path: "{{ _boot_directory }}/config.txt"
    regexp: "^{{ item.key }}="
    line: "{{ item.key }}={{ item.value }}"
  loop:
    - { key: "dtparam=i2c_arm", value: "on" }
    - { key: "dtparam=spi", value: "on" }
    - { key: "dtparam=i2s", value: "on" }
