---
- name: Include tuning/governor.yml
  ansible.builtin.import_tasks: tuning/governor.yml

- name: Include tuning/wireless.yml
  ansible.builtin.import_tasks: tuning/wireless.yml
  when:
    - ansible_wlan0 is defined
    - ansible_wlan0.active | bool

- name: Include tuning/udev.yml
  ansible.builtin.import_tasks: tuning/udev.yml

- name: Include tuning/io.yml
  ansible.builtin.import_tasks: tuning/io.yml

- name: Include tuning/zram.yml
  vars:
    # Debian Unstable hack
    _distribution_version: "{{ '99' if ansible_distribution == 'Debian' and ansible_distribution_version == 'n/a' else ansible_distribution_version }}"
  ansible.builtin.import_tasks: tuning/zram.yml
  when:
    not (ansible_distribution == 'Ubuntu' and _distribution_version is version('23.04', '<=') or
    ansible_distribution == 'Debian' and _distribution_version is version('12.0', '<='))

- name: Include tuning/sysctl.yml
  ansible.builtin.import_tasks: tuning/sysctl.yml

- name: Include tuning/fstab.yml
  ansible.builtin.import_tasks: tuning/fstab.yml

- name: Include tuning/numa.yml
  ansible.builtin.import_tasks: tuning/numa.yml
  when: "'Raspberry Pi 4' in ovos_installer_raspberrypi or 'Raspberry Pi 5' in ovos_installer_raspberrypi"
