---
- name: Add I/O scheduler rules for MMC and USB to udev
  ansible.builtin.lineinfile:
    path: /etc/udev/rules.d/60-mmc-usb-scheduler.rules
    line: "{{ item }}"
    owner: root
    group: root
    mode: "0644"
    create: true
  loop:
    - ACTION=="add|change", KERNEL=="mmc*", ATTR{queue/rotational}=="0", ATTR{queue/scheduler}="none"
    - ACTION=="add|change", KERNEL=="sd[a-z]", ATTR{removable}=="1", ATTR{queue/scheduler}="none"
  notify: Reload Udev

- name: Flush handlers udev
  ansible.builtin.meta: flush_handlers

- name: Block uninstall wireless
  when: ovos_installer_cleaning | bool
  tags:
    - uninstall
  block:
    - name: Remove 60-mmc-usb-scheduler.rules file
      ansible.builtin.file:
        path: /etc/udev/rules.d/60-mmc-usb-scheduler.rules
        state: absent
      notify: Reload Udev

    - name: Flush handlers udev (uninstall)
      ansible.builtin.meta: flush_handlers
