---
- name: Retrieve country based on ISP address
  ansible.builtin.uri:
    url: http://ip-api.com/json
    method: GET
    status_code: 200
    return_content: true
    headers:
      Content-Type: application/json
      accept: application/json
  register: _isp_data
  until: _isp_data.status == 200
  retries: 5
  delay: 3

- name: Share telemetry data
  ansible.builtin.uri:
    url: "{{ _ovos_installer_telemetry_url }}"
    method: POST
    body: "{{ lookup('ansible.builtin.template', 'telemetry.json.j2') }}"
    status_code: 200
    body_format: json
    headers:
      Content-Type: application/json
      accept: application/json
      user-agent: "{{ _ovos_installer_telemetry_user_agent }}"
  register: _push_telemetry_data
  until: _push_telemetry_data.status == 200
  retries: 5
  delay: 3
