---
- name: Include virtualenv/packages.yml
  ansible.builtin.import_tasks: virtualenv/packages.yml

- name: Include virtualenv/venv.yml
  ansible.builtin.import_tasks: virtualenv/venv.yml

- name: Include virtualenv/gui.yml
  ansible.builtin.import_tasks: virtualenv/gui.yml
  when: ovos_installer_feature_gui | bool or ovos_installer_cleaning | bool

- name: Include virtualenv/bus.yml
  ansible.builtin.import_tasks: virtualenv/bus.yml

- name: Include virtualenv/systemd.yml
  ansible.builtin.import_tasks: virtualenv/systemd.yml
