---
- name: Enable CRB repository
  ansible.builtin.command:
    cmd: dnf config-manager --enable crb
  changed_when: false
  when:
    - ansible_os_family == "RedHat"
    - ansible_distribution != "Fedora"

- name: Add EPEL repository
  ansible.builtin.dnf:
    name: epel-release
  when:
    - ansible_os_family == "RedHat"
    - ansible_distribution != "Fedora"

- name: Handle virtualenv package requirements (ovos/hivemind)
  ansible.builtin.apt:
    name:
      - build-essential
      - swig
      - libfann-dev
      - libasound2-dev
      - libpulse-dev
      - libportaudio2
      - mpg123
      - music123
      - sox
      - libsox-fmt-all
      - flac
      - vlc
      - libxslt1-dev
      - libopenblas-dev
      - pkg-config
      - libicu-dev
      - portaudio19-dev
    install_recommends: false
    state: "{{ ovos_installer_uninstall }}"
  when: ansible_os_family == "Debian"
  tags:
    - always

- name: Handle virtualenv package requirements (ovos/hivemind)
  ansible.builtin.dnf:
    name:
      - gcc-c++
      - swig
      - fann-devel
      - alsa-lib-devel
      - pulseaudio-libs-devel
      - portaudio
      - mpg123
      - sox
      - flac
      - vlc
      - openblas-serial
      - pkgconf-pkg-config
      - libicu-devel
      - portaudio-devel
    state: "{{ ovos_installer_uninstall }}"
  when: ansible_os_family == "RedHat"
  tags:
    - always

- name: Handle virtualenv package requirements (ovos/hivemind)
  community.general.zypper:
    name:
      - gcc-c++
      - swig
      - libfann-devel
      - alsa-lib-devel
      - libpulse-devel
      - libportaudio2
      - mpg123
      - sox
      - flac
      - vlc
      - libopenblas_serial-devel
      - portaudio-devel
    state: "{{ ovos_installer_uninstall }}"
  when: ansible_os_family == "Suse"
  tags:
    - always

- name: Handle virtualenv package requirements (ovos/hivemind)
  community.general.pacman:
    name:
      - base-devel
      - swig
      - libfann
      - alsa-lib
      - pulseaudio
      - portaudio
      - mpg123
      - sox
      - flac
      - vlc
      - libxslt
      - openblas
    state: "{{ ovos_installer_uninstall }}"
  when: ansible_os_family == "Arch"
  tags:
    - always
