---
- name: Enable CRB repository
  ansible.builtin.command:
    cmd: dnf config-manager --enable crb
  changed_when: false
  when:
    - ansible_os_family == "RedHat"
    - ansible_distribution != "Fedora"

- name: Add EPEL repository
  ansible.builtin.dnf:
    name: epel-release
  when:
    - ansible_os_family == "RedHat"
    - ansible_distribution != "Fedora"

- name: Handle virtualenv package requirements (ovos/hivemind)
  ansible.builtin.apt:
    name:
      - build-essential
      - swig
      - libfann-dev
      - libasound2-dev
      - libpulse-dev
      - libportaudio2
      - mpg123
      - music123
      - sox
      - libsox-fmt-all
      - flac
      - vlc
      - libxslt1-dev
      - libopenblas-dev
    state: "{{ ovos_installer_uninstall }}"
  when: ansible_os_family == "Debian"
  tags:
    - always

- name: Handle virtualenv package requirements (ovos/hivemind)
  ansible.builtin.dnf:
    name:
      - gcc-c++
      - swig
      - fann-devel
      - alsa-lib-devel
      - pulseaudio-libs-devel
      - portaudio
      - mpg123
      - sox
      - flac
      - vlc
      - libxslt
      - openblas-serial
    state: "{{ ovos_installer_uninstall }}"
  when: ansible_os_family == "RedHat"
  tags:
    - always
