---
collections:
  - name: ansible.posix
    version: 1.5.4
  - name: community.docker
    version: 3.7.0
  - name: community.general
    version: 8.3.0
  - name: kewlfft.aur
    version: 0.11.1
  - name: moreati.uv
    src: git+https://github.com/goldyfruit/ansible-uv
