---
- name: Open Voice OS Installer
  hosts: localhost
  connection: local
  gather_facts: false
  user: "{{ ovos_installer_user }}"
  become: true

  pre_tasks:
    - name: Gather reduced subset of facts
      ansible.builtin.setup:
        gather_subset:
          - "hardware"
          - "interfaces"
      tags:
        - always

  roles:
    - role: ovos_installer
