---
- name: Open Voice OS Installer
  hosts: localhost
  connection: local
  gather_facts: false
  user: "{{ ovos_installer_user }}"
  become: true

  pre_tasks:
    - name: Gather reduced subset of facts
      ansible.builtin.setup:
        gather_subset:
          - "hardware"
          - "interfaces"
      tags:
        - always

  roles:
    - role: ovos_hardware_mark2
      when:
        - ansible_distribution == "Debian"
        - ansible_distribution_version is version('11' '>=')
        - "'Raspberry Pi 4' in ovos_installer_raspberrypi or 'Raspberry Pi 5' in ovos_installer_raspberrypi"
        - "'tas5806' in ovos_installer_i2c_devices"
    - role: ovos_installer
