---
- name: Start Sound Server
  ansible.builtin.include_tasks: block-sound.yml
  when: not (ansible_distribution == 'Ubuntu' and ansible_distribution_version is version('23.04', '<=') or
        ansible_distribution == 'Debian' and ansible_distribution_version is version('12.0', '<='))

- name: Reload Systemd User
  become: true
  become_user: "{{ ovos_installer_user }}"
  ansible.builtin.systemd:
    daemon_reload: true
    scope: user

- name: Reload Systemd
  ansible.builtin.systemd:
    daemon_reload: true

- name: Reload Udev
  ansible.builtin.shell:
    cmd: |
      udevadm control --reload-rules && udevadm trigger
    executable: /bin/bash
  changed_when: false
