---
- name: Add {{ ovos_installer_user }} to docker group
  ansible.builtin.user:
    name: "{{ ovos_installer_user }}"
    groups: docker
    append: true

- name: Include docker/xhost.yml
  ansible.builtin.import_tasks: docker/xhost.yml
  when:
    - ovos_installer_feature_gui | bool
    - ovos_installer_display_server != 'N/A'

- name: Start docker service
  ansible.builtin.systemd_service:
    name: docker
    enabled: true
    state: started

- name: Clone ovos-docker and/or hivemind-docker repository
  ansible.builtin.git:
    repo: "{{ item.url }}"
    dest: "{{ _ovos_installer_working_directory }}/{{ item.dest }}"
    version: "{{ item.branch }}"
    force: true
  loop:
    - { "url": "{{ ovos_installer_ovos_docker_repo_url }}", "branch": "{{ ovos_installer_ovos_docker_repo_branch }}", "dest": "ovos-docker", "state": "{{ true if (ovos_installer_profile != 'satellite' or ovos_installer_cleaning | bool) else false }}" }
    - { "url": "{{ ovos_installer_hivemind_docker_repo_url }}", "branch": "{{ ovos_installer_hivemind_docker_repo_branch }}", "dest": "hivemind-docker", "state": "{{ true if (ovos_installer_profile == 'satellite' or ovos_installer_cleaning | bool) else false }}" }
  when: item.state | bool
  tags:
    - always
