---
- name: Include docker/setup-RedHat.yml
  ansible.builtin.import_tasks: docker/setup-RedHat.yml
  when: ansible_os_family == "RedHat"

- name: Include docker/setup-Debian.yml
  ansible.builtin.import_tasks: docker/setup-Debian.yml
  when: ansible_os_family == "Debian"

- name: Include docker/common.yml
  ansible.builtin.import_tasks: docker/common.yml

- name: Include docker/composer.yml
  ansible.builtin.import_tasks: docker/composer.yml
