---
- name: Retrieve installed packages
  ansible.builtin.package_facts:

- name: Include docker/setup-RedHat.yml
  ansible.builtin.import_tasks: docker/setup-RedHat.yml
  when:
    - ansible_os_family == "RedHat"
    - "'docker-ce' not in ansible_facts.packages"

- name: Include docker/setup-Debian.yml
  ansible.builtin.import_tasks: docker/setup-Debian.yml
  when:
    - ansible_os_family == "Debian"
    - "'docker-ce' not in ansible_facts.packages"

- name: Include docker/setup-Suse.yml
  ansible.builtin.import_tasks: docker/setup-Suse.yml
  when:
    - ansible_os_family == "Suse"
    - "'docker-ce' not in ansible_facts.packages"

- name: Include docker/setup-Arch.yml
  ansible.builtin.import_tasks: docker/setup-Arch.yml
  when:
    - ansible_os_family == "Arch"
    - "'docker' not in ansible_facts.packages"

- name: Include docker/common.yml
  ansible.builtin.import_tasks: docker/common.yml

- name: Include docker/composer.yml
  ansible.builtin.import_tasks: docker/composer.yml
