---
- name: Update package cache and install Docker Engine
  community.general.pacman:
    name:
      - docker
      - docker-compose
    update_cache: true

- name: Install xorg-xhost package
  community.general.pacman:
    name: xorg-xhost
  when: ovos_installer_display_server != "N/A"
