---
- name: Detect Debian based distribution
  ansible.builtin.set_fact:
    os_distribution: "{{ 'debian' if (ansible_distribution == 'Debian') else 'ubuntu' }}"

- name: Install required packages
  ansible.builtin.apt:
    name:
      - ca-certificates
      - gnupg
    install_recommends: false

- name: Retrieve Docker GPG repository key
  ansible.builtin.get_url:
    url: "https://download.docker.com/linux/{{ os_distribution }}/gpg"
    dest: "{{ _ovos_installer_debian_docker_gpg }}"
    owner: root
    group: root
    mode: "0644"

- name: Extract and replace gpg key with dearmor
  ansible.builtin.command:
    cmd: |
      gpg --dearmor {{ _ovos_installer_debian_docker_gpg }}
    creates: "{{ _ovos_installer_debian_docker_gpg }}.gpg"

- name: Add Docker repository
  vars:
    architecture: "{{ 'arm64' if ansible_architecture == 'aarch64' else 'amd64' }}"
  ansible.builtin.apt_repository:
    repo: "deb [arch={{ architecture }}, signed-by={{ _ovos_installer_debian_docker_gpg }}.gpg] https://download.docker.com/linux/{{ os_distribution }} {{ ansible_distribution_release }} stable"
    filename: /etc/apt/sources.list.d/docker
    update_cache: true

- name: Install Docker Engine
  ansible.builtin.apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    install_recommends: false
