name: Check code style and quality

on:
  pull_request:
    paths:
      - ansible/**
      - utils/**
  push:
    paths:
      - ansible/**
      - utils/**

jobs:
  ansible-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Ansible requirements
        run: |
          rm -rf ~/.ansible
          pip install ansible-playbook-grapher ansible ansible-lint
          sudo apt-get --no-install-recommends -y install graphviz
          ansible-galaxy collection install -r ansible/requirements.yml --force

      - name: Run ansible-lint
        working-directory: ./ansible
        run: ansible-lint

      - name: Retrieve task list from playbook
        env:
          ANSIBLE_LOCALHOST_WARNING: False
        run: |
          mkdir artifacts
          ansible-playbook --list-tasks ansible/site.yml > artifacts/list-tasks-site

      - name: Upload Ansible artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ansible-artifacts
          path: artifacts

  yaml-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run yaml-lint
        uses: ibiqlik/action-yamllint@v3
        with:
          config_file: ansible/.yamllint

  shell-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@master
        env:
          SHELLCHECK_OPTS: -x -s bash -e SC1091
