name: Scenarios on Ubuntu 24.04 x86_64

on:
  workflow_run:
    workflows:
      - "Check code style and quality"
      - "Testing shell components with BATS"
    types:
      - completed
  workflow_dispatch:

jobs:
  scenario-u2404-amd64-containers-dev-ovos-skills-gui:
    runs-on:
      - self-hosted
    steps:
      - name: Installer requirements
        run: |
          sudo apt-get update
          sudo apt-get --no-install-recommends install curl git -y

      - name: Uninstall existing instance
        run: |
          sh -c "curl -s https://raw.githubusercontent.com/OpenVoiceOS/ovos-installer/main/installer.sh -o installer.sh && chmod +x installer.sh && sudo ./installer.sh -u"

      - name: Scenario containers, development, ovos, skills
        run: |
          mkdir -p ~/.config/ovos-installer
          cat <<EOF >~/.config/ovos-installer/scenario.yaml
          ---
          uninstall: false
          method: containers
          channel: development
          profile: ovos
          features:
            skills: true
            extra_skills: true
            gui: true
          rapsberry_pi_tuning: false
          share_telemetry: false
          share_usage_telemetry: false
          EOF
          sh -c "curl -s https://raw.githubusercontent.com/OpenVoiceOS/ovos-installer/main/installer.sh -o installer.sh && chmod +x installer.sh && sudo ./installer.sh"
