name: Scenarios on Ubuntu 23.10 x86_64

on:
  workflow_run:
    workflows:
      - "Check code style and quality"
      - "Testing shell components with BATS"
    types:
      - completed
  workflow_dispatch:

jobs:
  scenario-u2310-amd64-containers-dev-ovos-skills:
    runs-on:
      - self-hosted
      - ubuntu-latest-amd64
    steps:
      - name: Installer requirements
        run: |
          sudo apt-get update
          sudo apt-get install curl git -y
          mkdir -p ~/.config/ovos-installer

      - name: Uninstall existing instance
        run: |
          sh -c "curl -s https://raw.githubusercontent.com/OpenVoiceOS/ovos-installer/main/installer.sh -o installer.sh && chmod +x installer.sh && sudo ./installer.sh -u"

      - name: Scenario containers, development, ovos, skills
        run: |
          cat <<EOF >~/.config/ovos-installer/scenario.yaml
          ---
          uninstall: false
          method: containers
          channel: development
          profile: ovos
          features:
            skills: true
            gui: false
          rapsberry_pi_tuning: false
          share_telemetry: false
          EOF
          sh -c "curl -s https://raw.githubusercontent.com/OpenVoiceOS/ovos-installer/main/installer.sh -o installer.sh && chmod +x installer.sh && sudo ./installer.sh"
